import { Vehicle, User, Booking, Review } from '@/types'

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Alex Fernando',
    email: 'alex@rento.app',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    role: 'owner',
    phone: '+94 77 123 4567',
    joinedAt: '2024-03-15',
    rating: 4.8,
    totalTrips: 42,
  },
  {
    id: 'u2',
    name: 'Nimal Perera',
    email: 'nimal@rento.app',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nimal',
    role: 'owner',
    phone: '+94 71 234 5678',
    joinedAt: '2024-06-10',
    rating: 4.6,
    totalTrips: 28,
  },
  {
    id: 'u3',
    name: 'Kavindi Silva',
    email: 'kavindi@rento.app',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kavindi',
    role: 'renter',
    phone: '+94 76 345 6789',
    joinedAt: '2025-01-20',
    rating: 4.9,
    totalTrips: 12,
  },
  {
    id: 'u4',
    name: 'Sahan Jayawardena',
    email: 'sahan@rento.app',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sahan',
    role: 'renter',
    phone: '+94 70 456 7890',
    joinedAt: '2025-04-05',
    rating: 4.7,
    totalTrips: 6,
  },
]

export const mockVehicles: Vehicle[] = [
  {
    id: 'v1',
    ownerId: 'u1',
    ownerName: 'Alex Fernando',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    title: 'Toyota Prius 2022 - Fuel Efficient',
    brand: 'Toyota',
    model: 'Prius',
    year: 2022,
    type: 'hatchback',
    transmission: 'automatic',
    fuelType: 'hybrid',
    seats: 5,
    pricePerDay: 45,
    location: 'Colombo 07',
    images: [
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0afa?w=800',
    ],
    description: 'Well-maintained Toyota Prius, perfect for city driving. Excellent fuel economy, comfortable interior with all modern features. GPS navigation included.',
    features: ['GPS Navigation', 'Bluetooth', 'Backup Camera', 'Cruise Control', 'USB Charging'],
    rating: 4.8,
    totalTrips: 35,
    available: true,
    createdAt: '2024-05-10',
  },
  {
    id: 'v2',
    ownerId: 'u1',
    ownerName: 'Alex Fernando',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    title: 'Honda Vezel 2023 - Compact SUV',
    brand: 'Honda',
    model: 'Vezel',
    year: 2023,
    type: 'suv',
    transmission: 'automatic',
    fuelType: 'hybrid',
    seats: 5,
    pricePerDay: 65,
    location: 'Colombo 03',
    images: [
      'https://images.unsplash.com/photo-1568844293986-8d0400f3a7b2?w=800',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
    ],
    description: 'Spacious and stylish Honda Vezel with hybrid technology. Perfect for family trips or weekend getaways. Smooth ride and excellent handling.',
    features: ['Sunroof', 'Leather Seats', 'GPS Navigation', 'Lane Assist', 'Apple CarPlay'],
    rating: 4.9,
    totalTrips: 22,
    available: true,
    createdAt: '2024-08-20',
  },
  {
    id: 'v3',
    ownerId: 'u2',
    ownerName: 'Nimal Perera',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nimal',
    title: 'Suzuki Alto 2021 - Budget Friendly',
    brand: 'Suzuki',
    model: 'Alto',
    year: 2021,
    type: 'hatchback',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 4,
    pricePerDay: 25,
    location: 'Kandy',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
    ],
    description: 'Economical and easy to drive Suzuki Alto. Great for navigating narrow city streets. Low fuel consumption and easy parking.',
    features: ['Air Conditioning', 'Power Steering', 'Central Locking', 'FM Radio'],
    rating: 4.5,
    totalTrips: 48,
    available: true,
    createdAt: '2024-04-15',
  },
  {
    id: 'v4',
    ownerId: 'u2',
    ownerName: 'Nimal Perera',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nimal',
    title: 'Toyota Hilux 2022 - Adventure Ready',
    brand: 'Toyota',
    model: 'Hilux',
    year: 2022,
    type: 'truck',
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 5,
    pricePerDay: 85,
    location: 'Galle',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=800',
    ],
    description: 'Powerful Toyota Hilux perfect for off-road adventures and trips to the south. 4WD, spacious cargo area. Ideal for surfing or camping trips.',
    features: ['4WD', 'Bull Bar', 'Roof Rack', 'Tow Bar', 'Dashcam', 'Bluetooth'],
    rating: 4.7,
    totalTrips: 18,
    available: true,
    createdAt: '2024-07-01',
  },
  {
    id: 'v5',
    ownerId: 'u1',
    ownerName: 'Alex Fernando',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    title: 'BMW 320i 2023 - Luxury Sedan',
    brand: 'BMW',
    model: '320i',
    year: 2023,
    type: 'luxury',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    pricePerDay: 120,
    location: 'Colombo 07',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800',
    ],
    description: 'Premium BMW 320i for those special occasions. Luxurious interior, powerful engine, and head-turning looks. Perfect for business trips or special events.',
    features: ['Leather Interior', 'Ambient Lighting', 'Parking Sensors', 'Premium Sound', 'Wireless Charging'],
    rating: 4.9,
    totalTrips: 15,
    available: true,
    createdAt: '2024-10-15',
  },
  {
    id: 'v6',
    ownerId: 'u2',
    ownerName: 'Nimal Perera',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nimal',
    title: 'Nissan Leaf 2023 - Full Electric',
    brand: 'Nissan',
    model: 'Leaf',
    year: 2023,
    type: 'electric',
    transmission: 'automatic',
    fuelType: 'electric',
    seats: 5,
    pricePerDay: 55,
    location: 'Colombo 05',
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
      'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800',
    ],
    description: 'Eco-friendly Nissan Leaf with zero emissions. Smooth, quiet ride perfect for city commuting. Home charger provided at pickup location.',
    features: ['Zero Emissions', 'ProPilot Assist', 'e-Pedal', 'Apple CarPlay', '360° Camera'],
    rating: 4.6,
    totalTrips: 20,
    available: true,
    createdAt: '2025-01-10',
  },
]

export const mockBookings: Booking[] = [
  {
    id: 'b1',
    vehicleId: 'v1',
    vehicleTitle: 'Toyota Prius 2022 - Fuel Efficient',
    vehicleImage: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
    renterId: 'u3',
    renterName: 'Kavindi Silva',
    ownerId: 'u1',
    ownerName: 'Alex Fernando',
    startDate: '2025-05-20',
    endDate: '2025-05-23',
    totalPrice: 135,
    status: 'confirmed',
    createdAt: '2025-05-15',
  },
  {
    id: 'b2',
    vehicleId: 'v4',
    vehicleTitle: 'Toyota Hilux 2022 - Adventure Ready',
    vehicleImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',
    renterId: 'u4',
    renterName: 'Sahan Jayawardena',
    ownerId: 'u2',
    ownerName: 'Nimal Perera',
    startDate: '2025-05-25',
    endDate: '2025-05-28',
    totalPrice: 255,
    status: 'pending',
    createdAt: '2025-05-18',
  },
  {
    id: 'b3',
    vehicleId: 'v5',
    vehicleTitle: 'BMW 320i 2023 - Luxury Sedan',
    vehicleImage: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    renterId: 'u3',
    renterName: 'Kavindi Silva',
    ownerId: 'u1',
    ownerName: 'Alex Fernando',
    startDate: '2025-04-10',
    endDate: '2025-04-12',
    totalPrice: 240,
    status: 'completed',
    createdAt: '2025-04-05',
  },
]

export const mockReviews: Review[] = [
  {
    id: 'r1',
    vehicleId: 'v1',
    renterId: 'u3',
    renterName: 'Kavindi Silva',
    renterAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kavindi',
    rating: 5,
    comment: 'Excellent vehicle! Very clean and fuel efficient. Alex was super responsive and the pickup was seamless.',
    createdAt: '2025-03-20',
  },
  {
    id: 'r2',
    vehicleId: 'v1',
    renterId: 'u4',
    renterName: 'Sahan Jayawardena',
    renterAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sahan',
    rating: 4,
    comment: 'Good car for city driving. GPS was very helpful. Would rent again.',
    createdAt: '2025-02-15',
  },
  {
    id: 'r3',
    vehicleId: 'v5',
    renterId: 'u3',
    renterName: 'Kavindi Silva',
    renterAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kavindi',
    rating: 5,
    comment: 'What a beautiful car! Made our anniversary dinner extra special. Perfectly maintained.',
    createdAt: '2025-04-12',
  },
]
